In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from matplotlib.colors import ListedColormap

In [2]:
class Perceptron(object):
    
    def __init__(self, eta = 0.01, n_iter = 50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
        #X의 shape = [n_samples, n_features] //훈련데이터
        #y의 shape = [n_samples] //target value
        
    def fit(self, X, y):
        #numpy random: 난수 발생 및 배열 생성 
        rgen = np.random.RandomState(self.random_state)
        
        #loc: 정규 분포의 평균 / scale: 표준편차
        #w_는 1d-array, 즉 [0, 0, 0 ... ]형태
        #w를 벡터 R(m+1)로 초기화: m은 feature 개수 //이유는 x0때문에
        #X.shape[0]-> 행 / X.shape[1] -> 열
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
        self.errors_ = []
        
        for _ in range(self.n_iter):
            errors = 0
            
            for xi, target in zip(X, y):
                
                #update = lr*(y-y^)
                update = self.eta * (target - self.predict(xi))
                
                #w0
                self.w_[0] += update
                
                #update 되기 이전 값들의 list
                errors += int(update != 0.0)
                
                #w1+...wm
                self.w_[1:] += update * xi

            self.errors_.append(errors)
                
        return self
    
    def net_input(self, X):
        
        #a 를 가중치, b 를 값 배열이라고 했을 때, 내적을 이용한 가중합 계산
        return np.dot(X, self.w_[1:]) + self.w_[0]
    
    def predict(self, X):
        
        #조건에 따라 슬라이싱 또는 값 반환
        #decision function
        return np.where(self.net_input(X) >= 0.0, 1, -1)

In [3]:
s = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
print('URL:', s)
df = pd.read_csv(s, header = None, encoding = 'utf-8')
df

URL: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data


0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
#seed 값이 0인 객체 생성
generator = np.random.RandomState(seed = 0)

#size 설정
new_random_number1 = generator.random(size = None)
new_random_number2 = generator.random(size = 5)
new_random_number3 = generator.random(size = (3, 4))

#size 별 출력
print(new_random_number1)
print(new_random_number2)
print(new_random_number3)

0.5488135039273248
[0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
[[0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664]
 [0.07103606 0.0871293  0.0202184  0.83261985]]


In [5]:
list_x = ([1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]) 

#3 X 4 matrix generated
X = np.array(list_x)
print(X)

#(4, 3)
X.shape
print()
print('shape:', X.shape)

#int(5) return
num = 1 + X.shape[1]
print('num', num)
print('num의 데이터 타입:', type(num))

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]

shape: (3, 4)
num 5
num의 데이터 타입: <class 'int'>


In [8]:
list_x = ([1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]) 

#3 X 4 matrix generated
X = np.array(list_x)
print('X의 모양')
print(X)

print('X shape:', X.shape)

y = np.array([[1], [1], [1]])
print('\n y의 모양')
print(y)
print('y shape:', y.shape)

print()

for xi, target in zip(X, y):
    print('\n xi:', xi)
    print('target:', target)

X의 모양
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
X shape: (3, 4)

 y의 모양
[[1]
 [1]
 [1]]
y shape: (3, 1)


 xi: [1 2 3 4]
target: [1]

 xi: [4 5 6 7]
target: [1]

 xi: [ 7  8  9 10]
target: [1]
