In [2]:
import numpy as np

In [20]:
#다차원 array 만들기 1
x = np.arange(12)
print(x, '\n')

x = x.reshape(4, 3)
print(x)
print(type(x), '\n')

#다차원 array 만들기 2
print(np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]))
print(type(x))

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'> 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'>


In [10]:
print('x의 차원:', x.ndim, '차원')
print('x의 원소 개수:', x.size, '개')
print('x의 데이터 타입:', x.dtype) #array는 무조건 1개 유형만 취할 수 있음
print('x의 행수 열수:', x.shape)
print('x는', x.shape[0], '행', x.shape[1], '열인 array이다.')

x의 차원: 2 차원
x의 원소 개수: 12 개
x의 데이터 타입: int32
x의 행수 열수: (4, 3)
x는 4 행 3 열인 array이다.


In [4]:
#np.array(형태, 데이터타입)
a = np.array([1, 2, 3, 4], np.float32)
b = np.array([[1], [2], [3], [4]], np.float32)
c = np.array([[1, 2, 3, 4]], np.float32)

print(a, a.shape, '\n') #4행, 열 없음
print(b, b.shape, '\n') #4행 1열
print(c, c.shape, '\n') #1행 4열

[1. 2. 3. 4.] (4,) 

[[1.]
 [2.]
 [3.]
 [4.]] (4, 1) 

[[1. 2. 3. 4.]] (1, 4) 



In [9]:
#3차원 이상 tensor
x = np.arange(12)
print(x)

x = x.reshape(2, 2, 3)
x

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [12]:
print('x의 차원:', x.ndim, '차원')
print('x의 원소 개수:', x.size, '개')
print('x의 데이터 타입:', x.dtype) 
print('x의 행수 열수:', x.shape)
print('x는', x.shape[1], '행', x.shape[2], '열이고', x.shape[0], '개 층을 가진 array이다.')

x의 차원: 3 차원
x의 원소 개수: 12 개
x의 데이터 타입: int32
x의 행수 열수: (2, 2, 3)
x는 2 행 3 열이고 2 개 층을 가진 array이다.


In [13]:
len(x)

2

In [21]:
test1 = np.array([1, 2, '3', 4])
print(test1)
print('test1 len:', len(test1))
print('test1 size:', test1.size, '\n')

test2 = np.array([[1, 2, 3], [4, 5, 6]])
print(test2)
print('test2 len:', len(test2))
print('test2 행수:', test2.shape[0])
print('test2 size:', test2.size, '\n')

test3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(test3)
print('test3 len:', len(test3))
print('test3 행수:', test3.shape[0])
print('test3 size:', test3.size, '\n')

test4 = np.array([[[1, 2], [3, 4]], [[1, 5], [6, 3]]])
print(test4)
print('test4 len:', len(test4))
print('test4의 층수:',test4.shape[0])
print('test4 size:', test4.size, '\n')

test5 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
              [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]]) 
print(test5)
print('test5 len:', len(test5))
print('test5의 층수:',test5.shape[0])
print('test5 size:', test5.size)
print('test5의 차원:',test5.ndim)

['1' '2' '3' '4']
test1 len: 4
test1 size: 4 

[[1 2 3]
 [4 5 6]]
test2 len: 2
test2 행수: 2
test2 size: 6 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
test3 len: 3
test3 행수: 3
test3 size: 9 

[[[1 2]
  [3 4]]

 [[1 5]
  [6 3]]]
test4 len: 2
test4의 층수: 2
test4 size: 8 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
test5 len: 2
test5의 층수: 2
test5 size: 24
test5의 차원: 3


In [2]:
x = np.arange(12)
x = x.reshape(4, 3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
#행 기준 평균(mean) -> 값이 3개
np.mean(x, axis = 0)

array([4.5, 5.5, 6.5])

In [4]:
#열 기준 평균 -> 값이 4개
np.mean(x, axis = 1)

array([ 1.,  4.,  7., 10.])

In [5]:
# ???? x는 행렬이므로 0, 1만 있다.
np.mean(x, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [22]:
#32 bits = 4 bytes -> 총 24 bytes
np.array([[1, 2, 3], [4.5, '6', '7']], dtype = np.float32).nbytes

24

In [23]:
#8 bits = 1 byte -> 총 6 bytes
np.array([[1, 2, 3], [4.5, '6', '7']], dtype = np.int8).nbytes

6

In [24]:
#64 bits = 8 bytes -> 총 48 bytes
np.array([[1, 2, 3], [4.5, '6', '7']], dtype = np.float64).nbytes

48