In [53]:
import numpy as np

In [50]:
#1d-array, 원소개수 5개
data = [1, 3, 5, 7, 9]
a = np.array(data)
print(a)
print(a.shape)

[1 3 5 7 9]
(5,)


In [51]:
#2d-array, 5 X 1 matrix
data = [[1], [3], [5], [7], [9]]
a = np.array(data)
print(a)
print(a.shape)

[[1]
 [3]
 [5]
 [7]
 [9]]
(5, 1)


In [52]:
#2d-array, 1 X 5 matrix
data = [[1, 3, 5, 7, 9]]
a = np.array(data)
print(a)
print(a.shape)

[[1 3 5 7 9]]
(1, 5)


In [6]:
#정답은 무엇일까요?
b = np.array([[1, 2, 3], [4, 5, 6]])
print('shape:', b.shape)
print('b[0]:', b[0])
print('b[1]:', b[1])
print('b[0, 0]:', b[0, 0])
print('b[1, 2]', b[1, 2])

shape: (2, 3)
b[0]: [1 2 3]
b[1]: [4 5 6]
b[0, 0]: 1
b[1, 2] 6


In [7]:
np.arange(3.0)

array([0., 1., 2.])

In [8]:
#정답은 무엇일까요?
print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [9]:
np.linspace(5, 10)

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.linspace(0, 1, 5, endpoint = False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [14]:
np.linspace(0, 100, num = 5)

array([  0.,  25.,  50.,  75., 100.])

In [15]:
np.linspace(0, 100, num = 5, dtype = int)

array([  0,  25,  50,  75, 100])

rand(d0, d1, …, dn)	Random values in a given shape.
randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.
randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive)
choice(a[, size, replace, p])	Generates a random sample from a given 1-D array

In [17]:
#0과 1사이 n개의 균등분포(uniform distribution)
np.random.rand(5)

array([0.01485437, 0.45276207, 0.32420211, 0.20901997, 0.41279583])

In [18]:
#0과 1사이 n개의 표준정규분포(standard normal distribution)
np.random.randn(5)

array([0.68510773, 0.38058704, 0.2784105 , 0.78939536, 1.14345498])

In [25]:
np.random.randint(10, 20, 5)

array([15, 15, 16, 13, 10])

In [33]:
#주어진 1d-array로부터 random sample 생성
#numpy.random.choice(a, size, replace, p)

#a와 p 개수는 같아야 함
#size는 a보다 작아야 함

#4는 절대 안나옴
np.random.choice(5, size = 3, replace = False, p = [0.2, 0.2, 0.5, 0.1, 0])

array([1, 2, 3])

In [37]:
#메난민 사태
weapons = ['worst', 'soso', 'good', 'best', 'superpower']
chance = [0.4, 0.4, 0.2, 0, 0]

#best와 superpower 무기는 절대 나오지 않는 ... 
for i in range(10):
    print(np.random.choice(weapons, p = chance, replace = False))

worst
soso
good
soso
worst
worst
good
worst
soso
good


In [41]:
#정답은 무엇일까요?
data = [1, 2, 3]
a = np.array(data)
a = 2 * a
print('2 * a: ', a, end = '\n\n')

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print('a + b:', a + b)
print('a * b:', a * b)
print('a / b:', a / b)
print('a % b:', a % b)
print('a - b:', a - b, end = '\n\n')

print(a == 2)
print(b > 20)
print((a == 2) & (b > 10))

2 * a:  [2 4 6]

a + b: [11 22 33]
a * b: [10 40 90]
a / b: [0.1 0.1 0.1]
a % b: [1 2 3]
a - b: [ -9 -18 -27]

[False  True False]
[False False  True]
[False  True False]


In [44]:
#masking
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a = np.array(data)
print(a)
print()

bool_i = np.array([[False, False, False], [True, True, True], [False, True, False]])
print(bool_i)
print()

b = a[bool_i]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[False False False]
 [ True  True  True]
 [False  True False]]

[4 5 6 8]


In [49]:
#홀수인 원소만 선택
b = a[a % 2 == 1]
print('홀수:', b)

#7보다 큰 원소만 선택
b = a[a > 7]
print('7보다 큰:', b)

#홀수면서 7보다 큰 원소
b = a[(a % 2 == 1) + (a > 7)]
print('홀수 & 7보다 큰:', b)

#홀수이고 7보다 큰 원소
b = a[(a % 2 == 1) * (a > 7)]
print('홀수 | 7보다 큰:', b)

홀수: [1 3 5 7 9]
7보다 큰: [8 9]
홀수 & 7보다 큰: [1 3 5 7 8 9]
홀수 | 7보다 큰: [9]
